export const lsToken = 'lsToken'
export const lsEmail = 'lsEmail'
export const lsName = 'lsName'
export const lsUserName = 'lsUserName'
export const lsProfilePhoto = 'lsProfilePhoto'
export const lsId = 'lsId'
export const lsRolName = 'lsRolName'
export const lsRol = 'lsRol'
export const lsImageBackground = 'lsImageBackground'

export const lsCode = 'lsCode'
export const lsModules = 'lsModules'
export const lsSchoolId = 'lsSchoolId'
export const lsSchoolUUID = 'lsSchoolUUID'
export const lsSchoolLogo = 'lsSchoolLogo'
export const lsSection = 'lsSection'
export const lsLevel = 'lsLevel'

export const lsAddres = 'lsAddress'
export const lsClave = 'lsClave'
export const lsRfc = 'lsRfc'
export const lsSchoolName = 'lsSchoolName'
export const lsFileCer = 'lsFileCer'
export const lsFilekey = 'lsFilekey'
